
#开发配置
spring:
  redis:
    #数据库索引
    database: 0
    host: 10.10.50.230
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 100
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000
  #数据源连接信息配置
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: 'jdbc:oracle:thin:@//10.10.50.172:1521/jianzai'
    username: c##jianzai
    password: admin
    initialSize: 10
    max-active: 100
    max-idle: 30
    min-idle: 1
    max-wait: 10000
    test-while-idle: true
    test-on-borrow: true
    test-on-return: true
    validation-query: SELECT 1
    validation-interval: 30000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    log-abandoned: true

#日志级别
logging:
  level:
    cn.com.thtf.dao: debug


#cas config
cas:
  server-url-prefix: http://www.leyou.com/cas
  server-login-url: http://www.leyou.com/cas/login
  client-host-url: http://www.leyou.com:9002
  validation-type: cas3
  authentication-url-patterns: /*
  validation-url-patterns: /*
  use-session: true
  redirect-after-validation: false

#cas client add url
cas-server:
  client-add-url: http://www.leyou.com/cas/addClient?ipAndPort={ipAndPort}&logoutUrl={logoutUrl}

login:
  success:
    path: http://www.leyou.com:9002/v1/log
  out:
    path: http://www.leyou.com:9002/login

ignore-pattern:
  paths: /ocean/message/create